---
title: "Untitled"
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
exps1 <- readRDS("exps1.rds")
exps2 <- readRDS("exps2.rds")
exps3 <- readRDS("exps3.rds")
exps4 <- readRDS("exps4.rds")
exps5 <- readRDS("exps5.rds")

```


# Misspecified Propensity Score and Misspecified Mean Learner

```{r}
K <- numeric(length(exps1))
mse <- numeric(length(exps1))
cvg <- numeric(length(exps1))
variance <- numeric(length(exps1))
bias <- numeric(length(exps1))
for(exp in seq_along(exps1)){
  cvg[exp] <- exps1[[exp]]$cvrg
  K[exp] <- exps1[[exp]]$est$cross_fit
  bias[exp] <-mean(exps1[[exp]]$ATE-exps1[[exp]]$TrueATE)
  mse[exp] <- mean((exps1[[exp]]$ATE-exps1[[exp]]$TrueATE)^2)
  variance[exp] <- var(exps1[[exp]]$ATE)
  
}
p1 <- cowplot::plot_grid(exps1[[1]]$plot(10), exps1[[2]]$plot(10), exps1[[3]]$plot(10))
p1

```

```{r}
tibble::tibble(K = K, cvg = cvg, mse = mse, bias = bias, variance = variance)

```



# Correctly specfied propensity Score and wrongly specified mean learner

```{r}
K <- numeric(length(exps2))
mse <- numeric(length(exps2))
cvg <- numeric(length(exps2))
variance <- numeric(length(exps2))
bias <- numeric(length(exps2))
for(exp in seq_along(exps2)){
  cvg[exp] <- exps2[[exp]]$cvrg
  K[exp] <- exps2[[exp]]$est$cross_fit
  bias[exp] <-mean(exps2[[exp]]$ATE-exps2[[exp]]$TrueATE)
  mse[exp] <- mean((exps2[[exp]]$ATE-exps2[[exp]]$TrueATE)^2)
  variance[exp] <- var(exps2[[exp]]$ATE)
  
}
p2 <- cowplot::plot_grid(exps2[[1]]$plot(10), exps2[[2]]$plot(10), exps2[[3]]$plot(10))
p2

```

```{r}
tibble::tibble(K = K, cvg = cvg, mse = mse, bias = bias, variance = variance)
```



# misspecfied propensity Score and RF mean learner



```{r}
K <- numeric(length(exps3))
mse <- numeric(length(exps3))
cvg <- numeric(length(exps3))
variance <- numeric(length(exps3))
bias <- numeric(length(exps3))
for(exp in seq_along(exps3)){
  cvg[exp] <- exps3[[exp]]$cvrg
  K[exp] <- exps3[[exp]]$est$cross_fit
  bias[exp] <-mean(exps3[[exp]]$ATE-exps3[[exp]]$TrueATE)
  mse[exp] <- mean((exps3[[exp]]$ATE-exps3[[exp]]$TrueATE)^2)
  variance[exp] <- var(exps3[[exp]]$ATE)
  
}
p3 <- cowplot::plot_grid(exps3[[1]]$plot(10), exps3[[2]]$plot(10), exps3[[3]]$plot(10))
p3

```

```{r}
tibble::tibble(K = K, cvg = cvg, mse = mse, bias = bias, variance = variance)
```




# correctly specified propensity Score and RF mean learner



```{r}
K <- numeric(length(exps4))
mse <- numeric(length(exps4))
cvg <- numeric(length(exps4))
variance <- numeric(length(exps4))
bias <- numeric(length(exps4))
for(exp in seq_along(exps4)){
  cvg[exp] <- exps4[[exp]]$cvrg
  K[exp] <- exps4[[exp]]$est$cross_fit
  bias[exp] <-mean(exps4[[exp]]$ATE-exps4[[exp]]$TrueATE)
  mse[exp] <- mean((exps4[[exp]]$ATE-exps4[[exp]]$TrueATE)^2)
  variance[exp] <- var(exps4[[exp]]$ATE)
  
}
p4 <- cowplot::plot_grid(exps4[[1]]$plot(10), exps4[[2]]$plot(10), exps4[[3]]$plot(10))
p4

```

```{r}
tibble::tibble(K = K, cvg = cvg, mse = mse, bias = bias, variance = variance)
```



# glmnet propensity Score and RF mean learner





```{r}
K <- numeric(length(exps5))
mse <- numeric(length(exps5))
cvg <- numeric(length(exps5))
variance <- numeric(length(exps5))
bias <- numeric(length(exps5))
for(exp in seq_along(exps5)){
  cvg[exp] <- exps5[[exp]]$cvrg
  K[exp] <- exps5[[exp]]$est$cross_fit
  bias[exp] <-mean(exps5[[exp]]$ATE-exps5[[exp]]$TrueATE)
  mse[exp] <- mean((exps5[[exp]]$ATE-exps5[[exp]]$TrueATE)^2)
  variance[exp] <- var(exps5[[exp]]$ATE)
  
}
p5 <- cowplot::plot_grid(exps5[[1]]$plot(10), exps5[[2]]$plot(10), exps5[[3]]$plot(10))
p5

```

```{r}
tibble::tibble(K = K, cvg = cvg, mse = mse, bias = bias, variance = variance)
```

